### ISSUE TITLE
Menú y Diagrama de Flujo

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105-cajero-automatico#5]
Durante las próximas dos semanas (**fecha límite 5 de abril**) debéis realizar dos aportaciones al repositorio:

- **Menú del programa**: debéis subir un fichero de código que implemente un menú provisional con el que interactuará el usuario de vuestro programa. Este menú debe contener las opciones necesarias para acceder a las funcionalidades previstas, aunque aún no realizará ninguna acción. El menú estará implementado mediante un bucle `switch-case` y se repetirá indefinidamente hasta que el usuario decida salir del programa.

- **Diagrama de Flujo**: debéis subir un fichero en formato [PDF](https://help.github.com/en/articles/rendering-pdf-documents), [GIF, JPEG o PNG](https://help.github.com/en/articles/rendering-and-diffing-images) (**no** se admiten documentos Word o similar) representando el diagrama de flujo previsto para vuestro programa. En [este enlace de Wikipedia](https://es.wikipedia.org/wiki/Diagrama_de_flujo) tenéis información sobre diagramas de flujo.

**Comment by almudenacostes** [comment]
![image](https://user-images.githubusercontent.com/47813213/55567575-3efd9980-56fe-11e9-83e6-8e43a85fcf4d.png)
Esa es la captura de pantalla del menu del programa realizado mediante un bucle switch-case. Y acontinuacion le adjunto un pdf con el diagrama de flujo;
[diagramadeflujo2.pdf](https://github.com/aigora/twE105-cajero-automatico/files/3044224/diagramadeflujo2.pdf)

**Comment by oscarperpinan** [comment]
Tanto el código como el diagrama tienen que estar en el repositorio, no como adjuntos a una _issue_. En cualquier caso, el código **nunca** se envía como captura de pantalla sino como texto plano en un fichero `.c`.

Por favor, consultad la documentación que tenéis disponible en el [punto de inicio](https://github.com/aigora/punto_inicio/wiki). Recordad que Julia y Miguel están disponibles en el laboratorio para resolver dudas de empleo de GitHub. Además, podéis echar un ojo a los repositorios de vuestros compañeros para aprender cómo lo están haciendo.

**Comment by oscarperpinan** [comment]
Para el diagrama de flujo os recomendamos la herramienta [draw.io](https://www.draw.io/). En el punto de inicio tenéis disponible un [tutorial](https://github.com/aigora/punto_inicio/wiki/6.1-C%C3%B3mo-realizar-un-diagrama-de-flujo).
